---
title: "ap3650_nyc_crime_data_visualization"
author: "Anita"
date: "March 13, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE, 
                      cache = TRUE)
```


```{r }
library(data.table)
library(vcdExtra)
library(extracat)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)

#fread("NYPD_Complaint_Data_Historic.csv",na.strings="",colClasses = c(PARKS_NM="c",HADEVELOPT="c"))->crime_df
#fread("NYPD_Complaint_Data_Historic.csv",na.strings="")->crime_df
crime_df <- read.csv("NYPD_Complaint_Data_Historic.csv", header=TRUE)
```

## Data Manipulations


```{r }

#Convert dates and times to correct format
crime_df$CMPLNT_FR_DT <- as.Date(crime_df$CMPLNT_FR_DT, format='%m/%d/%Y')
crime_df$CMPLNT_TO_DT <- as.Date(crime_df$CMPLNT_TO_DT, format='%m/%d/%Y')
crime_df$RPT_DT <- as.Date(crime_df$RPT_DT, format='%m/%d/%Y')

crime_df$CMPLNT_FR_TM <- as.POSIXct(crime_df$CMPLNT_FR_TM, format='%H:%M:%S')
crime_df$CMPLNT_TO_TM <- as.POSIXct(crime_df$CMPLNT_TO_TM, format='%H:%M:%S')

```
## Plots  
## Warm-up Plot :-) Bar Chart 
```{r}
  ggplot(crime_df,aes(LAW_CAT_CD)) +
    geom_bar() +
    ggtitle("Distribution of Crime Category")
```  

## Type of Offense  

```{r fig.height=10, fig.width=8}
  ggplot(crime_df,aes(PREM_TYP_DESC)) +
    geom_bar() +
    facet_wrap(~LAW_CAT_CD) +
    coord_flip() + 
    ggtitle("Crime Category Vs Place of Crime")
  

```

## Month and Time and Type of Crime

```{r fig.height = 10, fig.width=10}
  crime_df <- crime_df %>% drop_na()
  ggplot(crime_df, aes(LAW_CAT_CD)) +
  geom_bar() +
  #facet_wrap(~month(CMPLNT_FR_DT))
  #facet_wrap(~hour(CMPLNT_FR_TM))
  facet_grid(month(CMPLNT_FR_DT)~hour(CMPLNT_FR_TM))

```

## Time Series - Trend of Crime Rate 
```{r}
    crime_time <- crime_df %>%
                    filter(year(CMPLNT_FR_DT)>2005) %>%
                    group_by(Date=floor_date(CMPLNT_FR_DT, "year"),LAW_CAT_CD) %>%
                    summarize(count=n())

    ggplot(crime_time, aes(Date,count, color=LAW_CAT_CD))+
          geom_line() +
          ggtitle("Trend/Rate of Crimes in Each Category Across year")

    
    crime_time <- crime_df %>%
                    filter(year(CMPLNT_FR_DT)>2005) %>%
                    group_by(Date=floor_date(CMPLNT_FR_DT, "month"),LAW_CAT_CD) %>%
                    summarize(count=n())

    ggplot(crime_time, aes(Date,count, color=LAW_CAT_CD))+
          geom_line() +
          ggtitle("Trend/Rate of Crimes in Each Category Across year - sampled month-wise")

```
* Shows monthly pattern similar to Jingbo's
* Year pattern fluctuates 
```
## length of Crime Vs Type of Crime 
```{r}


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
